name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write  # Explicitly grant write permissions for contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow pystray pyinstaller

    - name: Download latest frl-toggle release
      shell: pwsh
      id: download_release
      run: |
        $repo = "FrogTheFrog/frl-toggle"
        $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/releases/latest"
        $asset = $release.assets | Where-Object { $_.name -match "\.exe$" }
        $downloadUrl = $asset.browser_download_url
        $exeName = $asset.name
        Invoke-WebRequest -Uri $downloadUrl -OutFile $exeName
        Write-Output "::set-output name=exe_name::$exeName"

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole frl-tray.py

    - name: Rename build folder to frl-tray
      run: |
        Rename-Item -Path "dist" -NewName "frl-tray"

    - name: Copy icons folder to frl-tray
      run: |
        Copy-Item -Recurse -Force .\icons .\frl-tray\icons

    - name: Move downloaded frl-toggle.exe to frl-tray
      run: |
        Move-Item ${{ steps.download_release.outputs.exe_name }} .\frl-tray\

    - name: Create release bundle
      run: |
        Compress-Archive -Path .\frl-tray\* -DestinationPath frl-tray.zip

    - name: Upload release bundle
      uses: actions/upload-artifact@v4
      with:
        name: frl-tray
        path: frl-tray.zip

    - name: Create GitHub release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}  # Use the branch name or tag name as the release name
        tag_name: ${{ github.ref_name }}     # Use the branch name or tag name as the tag
        files: frl-tray.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
